language: java
sudo: false
cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - jdk:
        - openjdk11
      env: jdk.release=11
    - jdk:
        - openjdk12
      env: jdk.release=12
    - jdk:
        - openjdk13
      env: jdk.release=13
    - jdk:
        - openjdk14
      env: jdk.release=14
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
install: true
branches:
  only:
    - master

script:
  - mvn clean install -Djdk.release=${release} -Pjdk9,enable-guicedee,enable-guicedee-projects,enable-guicedee-services,enable-guiced-hazelcast,enable-guiced-injection,enable-guiced-logmaster,enable-guiced-persistence,enable-guiced-persistence-btm,enable-guiced-rest,enable-guiced-servlets,enable-guiced-servlets-scoped,enable-guiced-swagger,enable-guiced-swagger-ui,enable-guiced-undertow,enable-guiced-webservices,enable-guiced-websockets,enable-jsf,enable-entityassist,enable-jakarta,enable-examples,enable-jackson,enable-xnio,enable-uadetector,enable-guicedee,enable-guicedee-services,enable-hazelcast,enable-hibernate,enable-jcache,enable-jstl,enable-standalone-services,enable-undertow,enable-ee4j,enable-guice,enable-commons,enable-jwebmp,enable-jwebmp-core,enable-plugins,enable-angular,enable-bootstrap,enable-jquery,enable-security,enable-javascript,enable-ion,enable-blueimp,enable-iconsets,enable-forms,enable-graphing,enable-effects,enable-jqxwidgets
after_success:
  - bash <(curl -s https://codecov.io/bash)
