language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
matrix:
  include:
    - jdk:
        - openjdk11
      env: jdk.release=11
    - jdk:
        - openjdk12
      env: jdk.release=12
    - jdk:
        - openjdk13
      env: jdk.release=13
    - jdk:
        - openjdk14
      env: jdk.release=14
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
branches:
  only:
    - master
install: true
script: mvn clean source:jar javadoc:jar install -DskipTests=true -Penable-guice
after_success:
  - bash <(curl -s https://codecov.io/bash)