language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
matrix:
  include:
    - jdk:
        - openjdk11
        - openjdk12
        - openjdk13
        - openjdk14
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
branches:
  only:
    - master
script: mvn clean source:jar javadoc:jar install -DskipTests=true -Penable-guice
after_success:
  - bash <(curl -s https://codecov.io/bash)