//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.30 at 07:10:45 AM BST 
//


package org.hibernate.jpamodelgen.xml.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hibernate.jpamodelgen.xml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hibernate.jpamodelgen.xml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Persistence }
     * 
     */
    public Persistence createPersistence() {
        return new Persistence();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Persistence.PersistenceUnit }
     * 
     */
    public Persistence.PersistenceUnit createPersistencePersistenceUnit() {
        return new Persistence.PersistenceUnit();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Persistence.PersistenceUnit.Properties }
     * 
     */
    public Persistence.PersistenceUnit.Properties createPersistencePersistenceUnitProperties() {
        return new Persistence.PersistenceUnit.Properties();
    }

    /**
     * Create an instance of {@link EntityMappings }
     * 
     */
    public EntityMappings createEntityMappings() {
        return new EntityMappings();
    }

    /**
     * Create an instance of {@link PersistenceUnitMetadata }
     * 
     */
    public PersistenceUnitMetadata createPersistenceUnitMetadata() {
        return new PersistenceUnitMetadata();
    }

    /**
     * Create an instance of {@link SequenceGenerator }
     * 
     */
    public SequenceGenerator createSequenceGenerator() {
        return new SequenceGenerator();
    }

    /**
     * Create an instance of {@link TableGenerator }
     * 
     */
    public TableGenerator createTableGenerator() {
        return new TableGenerator();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.NamedQuery }
     * 
     */
    public NamedQuery createNamedQuery() {
        return new NamedQuery();
    }

    /**
     * Create an instance of {@link NamedNativeQuery }
     * 
     */
    public NamedNativeQuery createNamedNativeQuery() {
        return new NamedNativeQuery();
    }

    /**
     * Create an instance of {@link NamedStoredProcedureQuery }
     * 
     */
    public NamedStoredProcedureQuery createNamedStoredProcedureQuery() {
        return new NamedStoredProcedureQuery();
    }

    /**
     * Create an instance of {@link SqlResultSetMapping }
     * 
     */
    public SqlResultSetMapping createSqlResultSetMapping() {
        return new SqlResultSetMapping();
    }

    /**
     * Create an instance of {@link MappedSuperclass }
     * 
     */
    public MappedSuperclass createMappedSuperclass() {
        return new MappedSuperclass();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Embeddable }
     * 
     */
    public Embeddable createEmbeddable() {
        return new Embeddable();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Converter }
     * 
     */
    public Converter createConverter() {
        return new Converter();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.EmptyType }
     * 
     */
    public EmptyType createEmptyType() {
        return new EmptyType();
    }

    /**
     * Create an instance of {@link PersistenceUnitDefaults }
     * 
     */
    public PersistenceUnitDefaults createPersistenceUnitDefaults() {
        return new PersistenceUnitDefaults();
    }

    /**
     * Create an instance of {@link AssociationOverride }
     * 
     */
    public AssociationOverride createAssociationOverride() {
        return new AssociationOverride();
    }

    /**
     * Create an instance of {@link AttributeOverride }
     * 
     */
    public AttributeOverride createAttributeOverride() {
        return new AttributeOverride();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Basic }
     * 
     */
    public Basic createBasic() {
        return new Basic();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.CascadeType }
     * 
     */
    public CascadeType createCascadeType() {
        return new CascadeType();
    }

    /**
     * Create an instance of {@link CollectionTable }
     * 
     */
    public CollectionTable createCollectionTable() {
        return new CollectionTable();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.ColumnResult }
     * 
     */
    public ColumnResult createColumnResult() {
        return new ColumnResult();
    }

    /**
     * Create an instance of {@link ConstructorResult }
     * 
     */
    public ConstructorResult createConstructorResult() {
        return new ConstructorResult();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Convert }
     * 
     */
    public Convert createConvert() {
        return new Convert();
    }

    /**
     * Create an instance of {@link DiscriminatorColumn }
     * 
     */
    public DiscriminatorColumn createDiscriminatorColumn() {
        return new DiscriminatorColumn();
    }

    /**
     * Create an instance of {@link ElementCollection }
     * 
     */
    public ElementCollection createElementCollection() {
        return new ElementCollection();
    }

    /**
     * Create an instance of {@link EmbeddableAttributes }
     * 
     */
    public EmbeddableAttributes createEmbeddableAttributes() {
        return new EmbeddableAttributes();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Embedded }
     * 
     */
    public Embedded createEmbedded() {
        return new Embedded();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.EmbeddedId }
     * 
     */
    public EmbeddedId createEmbeddedId() {
        return new EmbeddedId();
    }

    /**
     * Create an instance of {@link EntityListener }
     * 
     */
    public EntityListener createEntityListener() {
        return new EntityListener();
    }

    /**
     * Create an instance of {@link EntityListeners }
     * 
     */
    public EntityListeners createEntityListeners() {
        return new EntityListeners();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.EntityResult }
     * 
     */
    public EntityResult createEntityResult() {
        return new EntityResult();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.FieldResult }
     * 
     */
    public FieldResult createFieldResult() {
        return new FieldResult();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.ForeignKey }
     * 
     */
    public ForeignKey createForeignKey() {
        return new ForeignKey();
    }

    /**
     * Create an instance of {@link GeneratedValue }
     * 
     */
    public GeneratedValue createGeneratedValue() {
        return new GeneratedValue();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.IdClass }
     * 
     */
    public IdClass createIdClass() {
        return new IdClass();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Index }
     * 
     */
    public Index createIndex() {
        return new Index();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Inheritance }
     * 
     */
    public Inheritance createInheritance() {
        return new Inheritance();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.JoinColumn }
     * 
     */
    public JoinColumn createJoinColumn() {
        return new JoinColumn();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.JoinTable }
     * 
     */
    public JoinTable createJoinTable() {
        return new JoinTable();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Lob }
     * 
     */
    public Lob createLob() {
        return new Lob();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.ManyToMany }
     * 
     */
    public ManyToMany createManyToMany() {
        return new ManyToMany();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.ManyToOne }
     * 
     */
    public ManyToOne createManyToOne() {
        return new ManyToOne();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.MapKey }
     * 
     */
    public MapKey createMapKey() {
        return new MapKey();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.MapKeyClass }
     * 
     */
    public MapKeyClass createMapKeyClass() {
        return new MapKeyClass();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.MapKeyColumn }
     * 
     */
    public MapKeyColumn createMapKeyColumn() {
        return new MapKeyColumn();
    }

    /**
     * Create an instance of {@link MapKeyJoinColumn }
     * 
     */
    public MapKeyJoinColumn createMapKeyJoinColumn() {
        return new MapKeyJoinColumn();
    }

    /**
     * Create an instance of {@link NamedAttributeNode }
     * 
     */
    public NamedAttributeNode createNamedAttributeNode() {
        return new NamedAttributeNode();
    }

    /**
     * Create an instance of {@link NamedEntityGraph }
     * 
     */
    public NamedEntityGraph createNamedEntityGraph() {
        return new NamedEntityGraph();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.NamedSubgraph }
     * 
     */
    public NamedSubgraph createNamedSubgraph() {
        return new NamedSubgraph();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.OneToMany }
     * 
     */
    public OneToMany createOneToMany() {
        return new OneToMany();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.OneToOne }
     * 
     */
    public OneToOne createOneToOne() {
        return new OneToOne();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.OrderColumn }
     * 
     */
    public OrderColumn createOrderColumn() {
        return new OrderColumn();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.PostLoad }
     * 
     */
    public PostLoad createPostLoad() {
        return new PostLoad();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.PostPersist }
     * 
     */
    public PostPersist createPostPersist() {
        return new PostPersist();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.PostRemove }
     * 
     */
    public PostRemove createPostRemove() {
        return new PostRemove();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.PostUpdate }
     * 
     */
    public PostUpdate createPostUpdate() {
        return new PostUpdate();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.PrePersist }
     * 
     */
    public PrePersist createPrePersist() {
        return new PrePersist();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.PreRemove }
     * 
     */
    public PreRemove createPreRemove() {
        return new PreRemove();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.PreUpdate }
     * 
     */
    public PreUpdate createPreUpdate() {
        return new PreUpdate();
    }

    /**
     * Create an instance of {@link PrimaryKeyJoinColumn }
     * 
     */
    public PrimaryKeyJoinColumn createPrimaryKeyJoinColumn() {
        return new PrimaryKeyJoinColumn();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.QueryHint }
     * 
     */
    public QueryHint createQueryHint() {
        return new QueryHint();
    }

    /**
     * Create an instance of {@link SecondaryTable }
     * 
     */
    public SecondaryTable createSecondaryTable() {
        return new SecondaryTable();
    }

    /**
     * Create an instance of {@link StoredProcedureParameter }
     * 
     */
    public StoredProcedureParameter createStoredProcedureParameter() {
        return new StoredProcedureParameter();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Transient }
     * 
     */
    public Transient createTransient() {
        return new Transient();
    }

    /**
     * Create an instance of {@link UniqueConstraint }
     * 
     */
    public UniqueConstraint createUniqueConstraint() {
        return new UniqueConstraint();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link org.hibernate.jpamodelgen.xml.jaxb.Persistence.PersistenceUnit.Properties.Property }
     * 
     */
    public Persistence.PersistenceUnit.Properties.Property createPersistencePersistenceUnitPropertiesProperty() {
        return new Persistence.PersistenceUnit.Properties.Property();
    }

}
